### PR TITLE
fix: add helper getPositionAt to fix incorrect loc

### LINKED ISSUE #292: [bug] restored loc column is still incorrect when `startLine` is not 1
https://github.com/mdx-js/eslint-mdx/blob/master/packages/eslint-mdx/src/helpers.ts#L122-L130

### PR DESCRIPTION
**Pull request by JounQin**
close #292

The following has been resolved!

<del>
I don't know if there is a better and cleaner way without source `code` or `lines`.

---

OK, I found maybe we have to use this approach because the loc column of start node could be incorrect as described at https://github.com/mdx-js/eslint-mdx/issues/279#issuecomment-791531564, while the start offset is always correct.
</del>

### CODE REVIEW

File: packages/eslint-mdx/src/helpers.ts [hunk 1]
```diff
@@ -146,16 +146,17 @@ export const restoreNodeLocation = <T>(
...
   }
 
-  const { range } = node
+  let {
+    range: [start, end],
+  } = node
 
-  const start = range[0] + offset
-  const end = range[1] + offset
+  const range = [(start += offset), (end += +offset)] as const
```
Comment (ChristianMurphy) [inline packages/eslint-mdx/src/helpers.ts]: The extra `+` looks like a typo?

```suggestion
  const range = [(start += offset), (end += offset)] as const
```

**Review by ChristianMurphy — APPROVED** [review]

File: packages/eslint-mdx/src/helpers.ts (hunk 1 above)
Comment (JounQin) [reply packages/eslint-mdx/src/helpers.ts]: Done

**Comment by JounQin** [comment]
@wooorm ready for a patch release!

**Comment by wooorm** [comment]
@JounQin I can’t release, there’s a typescript error when running `tsc -b`:

```
Error: @rollup/plugin-typescript TS2569: Type 'IterableIterator<[number, string]>' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators.
    at error (~/eslint-mdx/node_modules/rollup/dist/shared/rollup.js:5279:30)
    at throwPluginError (~/eslint-mdx/node_modules/rollup/dist/shared/rollup.js:18240:12)
    at Object.error (~/eslint-mdx/node_modules/rollup/dist/shared/rollup.js:18847:24)
    at Object.error (~/eslint-mdx/node_modules/rollup/dist/shared/rollup.js:18409:38)
    at ~/eslint-mdx/node_modules/@rollup/plugin-typescript/dist/index.js:27:21
    at Array.forEach (<anonymous>)
    at emitDiagnostics (~/eslint-mdx/node_modules/@rollup/plugin-typescript/dist/index.js:22:10)
    at Object.transform (~/eslint-mdx/node_modules/@rollup/plugin-typescript/dist/index.js:465:17)
    at ~/eslint-mdx/node_modules/rollup/dist/shared/rollup.js:19049:25 {
  pluginCode: 'TS2569',
  loc: {
    column: 37,
    line: 103,
    file: '~/eslint-mdx/packages/eslint-mdx/src/helpers.ts'
  },
  frame: '\n' +
    "\x1B[7m103\x1B[0m   for (const [index, { length }] of code.split('\\n').entries()) {\n" +
    '\x1B[7m   \x1B[0m \x1B[91m                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~\x1B[0m\n',
  id: '~/eslint-mdx/packages/eslint-mdx/src/helpers.ts',
  hook: 'transform',
  code: 'PLUGIN_ERROR',
  plugin: 'typescript',
  watchFiles: [
    '~/eslint-mdx/packages/eslint-mdx/src/index.ts',
    '~/eslint-mdx/packages/eslint-mdx/src/helpers.ts',
    '~/eslint-mdx/packages/eslint-mdx/src/parser.ts',
    '~/eslint-mdx/packages/eslint-mdx/src/regexp.ts',
    '~/eslint-mdx/packages/eslint-mdx/src/traverse.ts',
    '~/eslint-mdx/packages/eslint-mdx/src/types.ts'
  ]
}
```

File: packages/eslint-mdx/src/helpers.ts (hunk 1 above)
Comment (JounQin) [reply packages/eslint-mdx/src/helpers.ts]: raised a new rule proposal for it https://github.com/typescript-eslint/typescript-eslint/issues/3204

**Comment by wooorm** [comment]
Released!
