### PR TITLE
feat: bump (dev)Dependencies, fix: consider first jsx node as open tag - close #272

### LINKED ISSUE #272: `Parsing error: unknown jsx node` when newlines are between nested jsx nodes
### Subject of the issue

When newlines exist between 2 nested jsx nodes, linting of the file fails with `Parsing error: unknown jsx node`.

### Your environment

*   **OS**: MacOS 10.15.7, CodeSandbox
*   **Packages**:
    * `eslint@7.20.0`
    * `eslint-plugin-mdx@1.8.2`
    * `eslint-plugin-react@7.22.0`
*   **Env**:
    * `node@14.15.5`, (10.23.0 in CodeSandbox)
    * `yarn@1.22.10`

### Steps to reproduce

[codesandbox](https://codesandbox.io/s/youthful-keller-bj6c1?file=/package.json:253-342)

Error
```mdx
<div>
  <p>test</p> 

  <p>test</p>
</div>
```

No Error
```mdx
<div>
  <p>test</p> 
  <p>test</p>
</div>
```

### Expected behaviour

This should pass lint without error

### Actual behaviour

Lint fails with error

### PR DESCRIPTION
**Pull request by JounQin**
fix #272

the parsed remark-mdx jsx nodes are not precise, but it will be resolved in v2

### CODE REVIEW

File: packages/eslint-mdx/src/traverse.ts [hunk 1]
```diff
@@ -56,10 +56,16 @@ export class Traverse {
...
-            !isComment(value) &&
-            !isSelfClosingTag(value) &&
-            !isOpenCloseTag(value)
+            isComment(value) ||
+            isSelfClosingTag(value) ||
+            isOpenCloseTag(value)
           ) {
+            jsxNodes.push(node)
+          } else {
+            // #272, we consider the first jsx node as open tag although it's not precise
```
Comment (JounQin) [inline packages/eslint-mdx/src/traverse.ts:65]: The most important code change is the following three lines.

File: packages/eslint-mdx/src/traverse.ts [hunk 2]
```diff
@@ -56,28 +56,37 @@ export class Traverse {
           // prettier-ignore
           /* istanbul ignore next */
           else if (
-            !isComment(value) &&
-            !isSelfClosingTag(value) &&
-            !isOpenCloseTag(value)
+            isComment(value) ||
```
Comment (JounQin) [inline packages/eslint-mdx/src/traverse.ts:59]: The most important code change is these lines.

File: packages/eslint-mdx/src/traverse.ts [hunk 3]
```diff
@@ -56,28 +56,37 @@ export class Traverse {
           // prettier-ignore
           /* istanbul ignore next */
           else if (
```
Comment (JounQin) [inline packages/eslint-mdx/src/traverse.ts:58]: The most important code change is the following lines.

https://github.com/mdx-js/eslint-mdx/pull/273/files#diff-b32281cf6a9e6127915ce948b00b48377679fa085e7d45d451fe7769ae9ee351R58-R89

**Comment by JounQin** [comment]
@wooorm @ChristianMurphy

**Comment by wooorm** [comment]
@JounQin What’s the reason for the ping? A code review or something else? If the first: I’ve never really looked into the code of this project much and this PR also seems to contain several code-style changes, so this looks okay but I’m not really sure what part I should focus on?

File: packages/eslint-mdx/src/parser.ts [hunk 4]
```diff
@@ -191,7 +193,9 @@ export class Parser {
 
           let normalized = this.normalizeJsxNode(node, parent, options)
           normalized = Array.isArray(normalized) ? normalized : [normalized]
-          normalized.forEach(_node => this._nodeToAst(_node, options))
+          for (const _node of normalized) {
```
Comment (ChristianMurphy) [inline packages/eslint-mdx/src/parser.ts:196]: I'm curious why `_` prefix is used here but not else where.
Usually it denotes an attribute which is publicly visible, but should be treated as a private member.
But this appears to be already block scoped :thinking:

File: packages/eslint-mdx/src/traverse.ts [hunk 5]
```diff
@@ -56,28 +56,37 @@ export class Traverse {
...
+            isComment(value) ||
+            isSelfClosingTag(value) ||
+            isOpenCloseTag(value)
           ) {
+            jsxNodes.push(node)
+          } else {
+            // #272, we consider the first jsx node as open tag although it's not precise
+            if (!index) {
+              offset++
+            }
```
Comment (ChristianMurphy) [inline packages/eslint-mdx/src/traverse.ts:68]: I'm not quite following this, is this an needed because MDX 1 does not having estree nodes?

File: packages/eslint-mdx/src/parser.ts (hunk 4 above)
Comment (JounQin) [reply packages/eslint-mdx/src/parser.ts:196]: There is a top shadow `node`, maybe I should rename it to `normalizedNode`?

File: packages/eslint-mdx/src/traverse.ts (hunk 5 above)
Comment (JounQin) [reply packages/eslint-mdx/src/traverse.ts:68]: Yes, `<div><p></p>` is parsed as a single jsx node, but I imagined it should be two jsx nodes `<div>` and `<p></p>`

File: packages/eslint-mdx/src/parser.ts (hunk 4 above)
Comment (ChristianMurphy) [reply packages/eslint-mdx/src/parser.ts:196]: > `normalizedNode`

that could be a bit clearer

**Comment by JounQin** [comment]
@wooorm I've highlighted the important changes at https://github.com/mdx-js/eslint-mdx/pull/273#discussion_r579675935 .

**Review by ChristianMurphy — APPROVED** [review]

**Comment by wooorm** [comment]
I’m generally fine with this, because I trust your opinion more that mine on this project! I’d guess the `// prettier-ignore` line above it might be a bad sign though, so maybe some extra tests to check that it works would be good

**Comment by JounQin** [comment]
> I’m generally fine with this, because I trust your opinion more that mine on this project! I’d guess the `// prettier-ignore` line above it might be a bad sign though, so maybe some extra tests to check that it works would be good

Did you me the following `istanbul ignore next`? It should be moved to another place actually.

**Comment by JounQin** [comment]
@mdx-js/releasers Please help to release a new version.

**Comment by JounQin** [comment]
@wooorm Any time to cut a release?

**Comment by wooorm** [comment]
Released!
